| ID | Name & Location | Description & usage | Cardinality & Level |
| -- | --------------- | ------------------- | ------------------- |
| <a name="CSIP31"></a>**CSIP31** | **Administrative metadata** <br/> `mets/amdSec` | If administrative / preservation metadata is available, it must be described using the administrative metadata section (`<amdSec>`) element. <br/> All administrative metadata is present in a single `<amdSec>` element. <br/> It is possible to transfer metadata in a package using just the descriptive metadata section and/or administrative metadata section. | **0..1** <br/> SHOULD |
| <a name="CSIP32"></a>**CSIP32** | **Digital provenance metadata** <br/> `mets/amdSec/digiprovMD` | For recording information about preservation the standard PREMIS is used. It is mandatory to include one `<digiprovMD>' element for each piece of PREMIS metadata. <br/> The use if PREMIS in METS is following the recommendations in  <br/> 2017 version of PREMIS in METS Guidelines | **0..n** <br/> SHOULD |
| <a name="CSIP33"></a>**CSIP33** | **Digital provenance metadata identfier** <br/> `mets/amdSec/digiprovMD/@ID` | An `xml:id` identifier for the digital provenance metadata section `mets/amdSec/digiprovMD` used for internal package references. It must be unique within the package. | **1..1** <br/> MUST |
| <a name="CSIP34"></a>**CSIP34** | **Status of the digital provenance metadata** <br/> `mets/amdSec/digiprovMD/@STATUS` | Indicates the status of the package using a fixed vocabulary. <br/> **See also:** <a href="#VocabularyStatus" >dmdSec status</a> | **0..1** <br/> SHOULD |
| <a name="CSIP35"></a>**CSIP35** | **Reference to the document with the digital provenance metdata** <br/> `mets/amdSec/digiprovMD/mdRef` | Reference to the digital provenance metadata file stored in the “metadata” section of the IP. | **0..1** <br/> SHOULD |
| <a name="CSIP36"></a>**CSIP36** | **Type of locator** <br/> `mets/amdSec/digiprovMD/mdRef[@LOCTYPE='URL']` | The locator type is always used with the value "URL" from the vocabulary in the attribute. | **1..1** <br/> MUST |
| <a name="CSIP37"></a>**CSIP37** | **Type of link** <br/> `mets/amdSec/digiprovMD/mdRef[@xlink:type='simple']` | Attribute used with the value “simple”. Value list is maintained by the xlink standard. | **1..1** <br/> MUST |
| <a name="CSIP38"></a>**CSIP38** | **Resource location** <br/> `mets/amdSec/digiprovMD/mdRef/@xlink:href` | The actual location of the resource. This specification recommends recording a URL type filepath within this attribute. | **1..1** <br/> MUST |
| <a name="CSIP39"></a>**CSIP39** | **Type of metadata** <br/> `mets/amdSec/digiprovMD/mdRef/@MDTYPE` | Specifies the type of metadata in the referenced file. Values are taken from the list provided by the METS. | **1..1** <br/> MUST |
| <a name="CSIP40"></a>**CSIP40** | **File mime type** <br/> `mets/amdSec/digiprovMD/mdRef/@MIMETYPE` | The IANA mime type for the referenced file. <br/> **See also:** <a href="#VocabularyIANAmediaTypes" >IANA media types</a> | **1..1** <br/> MUST |
| <a name="CSIP41"></a>**CSIP41** | **File size** <br/> `mets/amdSec/digiprovMD/mdRef/@SIZE` | Size of the referenced file in bytes. | **1..1** <br/> MUST |
| <a name="CSIP42"></a>**CSIP42** | **File creation date** <br/> `mets/amdSec/digiprovMD/mdRef/@CREATED` | Creation date of the referenced file. | **1..1** <br/> MUST |
| <a name="CSIP43"></a>**CSIP43** | **File checksum** <br/> `mets/amdSec/digiprovMD/mdRef/@CHECKSUM` | The checksum of the referenced file. | **1..1** <br/> MUST |
| <a name="CSIP44"></a>**CSIP44** | **File checksum type** <br/> `mets/amdSec/digiprovMD/mdRef/@CHECKSUMTYPE` | The type of checksum following the value list in the standard which used for the referenced file. | **1..1** <br/> MUST |
| <a name="CSIP45"></a>**CSIP45** | **Rights metadata** <br/> `mets/amdSec/rightsMD` | A simple rights statement may be used to describe general permissions for the package. Individual representations should state their specific rights in their representation METS file. <br/> Available standards include  <br/> RightsStatements.org <br/>  ,  <br/> Europeana rights statements info <br/> ),  <br/> METS Rights Schema <br/>  created and maintaned by the METS Board, the rights part of  <br/> PREMIS <br/>  as well as own local rights statements in use. | **0..n** <br/> MAY |
| <a name="CSIP46"></a>**CSIP46** | **Rights metadata identifier** <br/> `mets/amdSec/rightsMD/@ID` | An `xml:id` identifier for the rights metadata section (`<rightsMD>`) used for internal package references. It must be unique within the package. | **1..1** <br/> MUST |
| <a name="CSIP47"></a>**CSIP47** | **Status of the rights metadata** <br/> `mets/amdSec/rightsMD/@STATUS` | Indicates the status of the package using a fixed vocabulary. <br/> **See also:** <a href="#VocabularyStatus" >dmdSec status</a> | **0..1** <br/> SHOULD |
| <a name="CSIP48"></a>**CSIP48** | **Reference to the document with the rights metadata** <br/> `mets/amdSec/rightsMD/mdRef` | Reference to the rights metadata file stored in the “metadata” section of the IP. | **0..1** <br/> SHOULD |
| <a name="CSIP49"></a>**CSIP49** | **Type of locator** <br/> `mets/amdSec/rightsMD/mdRef[@LOCTYPE=`URL`]` | The locator type is always used with the value "URL" from the vocabulary in the attribute. | **1..1** <br/> MUST |
| <a name="CSIP50"></a>**CSIP50** |  <br/> `mets/amdSec/rightsMD/mdRef[@xlink:type='simple']` | Attribute used with the value “simple”. Value list is maintained by the xlink standard. | **1..1** <br/> MUST |
| <a name="CSIP51"></a>**CSIP51** | **Resource location** <br/> `mets/amdSec/rightsMD/mdRef/@xlink:href` | The actual location of the resource. We  recommend recording a URL type filepath within this attribute. | **1..1** <br/> MUST |
| <a name="CSIP52"></a>**CSIP52** | **Type of metadata** <br/> `mets/amdSec/rightsMD/mdRef/@MDTYPE` | Specifies the type of metadata in the referenced file. Value is taken from the list provided by the METS. | **1..1** <br/> MUST |
| <a name="CSIP53"></a>**CSIP53** | **File mime type** <br/> `mets/amdSec/rightsMD/mdRef/@MIMETYPE` | The IANA mime type for the referenced file. <br/> **See also:** <a href="#VocabularyIANAmediaTypes" >IANA media types</a> | **1..1** <br/> MUST |
| <a name="CSIP54"></a>**CSIP54** | **File size** <br/> `mets/amdSec/rightsMD/mdRef/@SIZE` | Size of the referenced file in bytes. | **1..1** <br/> MUST |
| <a name="CSIP55"></a>**CSIP55** | **File creation date** <br/> `mets/amdSec/rightsMD/mdRef/@CREATED` | Creation date of the referenced file. | **1..1** <br/> MUST |
| <a name="CSIP56"></a>**CSIP56** | **File checksum** <br/> `mets/amdSec/rightsMD/mdRef/@CHECKSUM` | The checksum of the referenced file. | **1..1** <br/> MUST |
| <a name="CSIP57"></a>**CSIP57** | **File checksum type** <br/> `mets/amdSec/rightsMD/mdRef/@CHECKSUMTYPE` | The type of checksum following the value list in the standard which used for the referenced file. | **1..1** <br/> MUST |
